build:
  image: node:latest
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -O -rav dist/ $SSH_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $SSH_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && npm i && $START_SCRIPT"
  only:
    - master
